//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module lab12(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,
	
	//////////// LED //////////
	output		     [9:0]		LEDR
);

wire i = ~KEY[0];
wire d = ~KEY[1];
circuit c1(.i(i), .d(d) , .clk(cnt[25]), .LEDR(LEDR[1:0]), .sOut());


wire [31:0] cnt;
counter c0(.clk(CLOCK_50), .count(cnt));

endmodule

module circuit(input i, input d , input clk,output [1:0] LEDR, output [1:0] sOut);

	reg [1:0] s;
	wire [1:0] n;

	// state register
	always @(posedge clk) 
	begin
		s <= n;
	end
	
	// combinational circuit
	assign LEDR[1] = s[1];
	assign LEDR[0] = s[0];

	assign n[1] = (~s[1] & ~s[0] & ~i & d) | (~s[1] & s[0] & i & ~d) | (s[1] &  ~i & ~d) | (s[1] & s[0] & ~i ) | (s[1] & s[0] & d) | (s[1] & i & d) | (s[1] & ~s[0] & i ) | (~s[1] & s[0] & i & ~d);
	assign n[0] = ( s[0] & ~i & ~d) | ( ~s[0] & ~i & d) | ( s[0] & i & d) | ( ~s[0] & i & ~d);
	assign sOut = s;

endmodule

// counter module definition
module counter (input clk, output reg [31:0] count);
	
	always@(posedge clk) 
	begin
		count = count + 32'b1;
	end
	
endmodule