# Geliştirme ortamında doğrulama linkinin base URL'i
app.url=http://localhost:8080

# (Şimdilik SMTP yok, dummy servis kullanıyoruz. İleride MailDev/SMTP buraya gelecek.)
# Örnek MailDev ayarlarını sonra ekleyeceğiz:
# spring.mail.host=localhost
# spring.mail.port=1025
# spring.mail.properties.mail.smtp.auth=false
# spring.mail.properties.mail.smtp.starttls.enable=false
