//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module lab11(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,
	
	//////////// LED //////////
	output		     [9:0]		LEDR
);

wire b = ~KEY[0];
circuit c1(.b(b), .clk(cnt[25]), .LEDR(LEDR[2:0]), .sOut());


wire [31:0] cnt;
counter c0(.clk(CLOCK_50), .count(cnt));

endmodule

module circuit(input b, input clk,output [2:0] LEDR, output [2:0] sOut);

	reg [2:0] s;
	wire [2:0] n;

	// state register
	always @(posedge clk) 
	begin
		s <= n;
	end
	
	// combinational circuit
	assign LEDR[2] = (s[2] & ~s[1] & s[0]) | (s[2] & s[1] & s[0]);
	assign LEDR[1] = (~s[2] & s[1] & ~s[0]) | (~s[2] & s[1] & s[0]) | (s[2] & s[1] & s[0]);
	assign LEDR[0] = (~s[2] & s[1] & s[0]) | (s[2] & ~s[1] & s[0]) | (s[2] & s[1] & s[0]);

	assign n[2] = b& (~s[2] & s[1] & s[0])  | (s[2] & ~s[1] & ~s[0]) | (s[2] & ~s[1] & s[0]) | (s[2] & s[1] & ~s[0]);
	assign n[1] = b& (~s[2] & ~s[1] & s[0])  | (~s[2] & s[1] & ~s[0]) | (s[2] & ~s[1] & s[0]) | (s[2] & s[1] & ~s[0]);
	assign n[0] = b& (~s[2] & ~s[1] & ~s[0])  | (~s[2] & s[1] & ~s[0]) | (s[2] & ~s[1] & ~s[0]) | (s[2] & s[1] & ~s[0]);
	assign sOut = s;

endmodule

// counter module definition
module counter (input clk, output reg [31:0] count);
	
	always@(posedge clk) 
	begin
		count = count + 32'b1;
	end
	
endmodule